@Backend_HostAddress = https://localhost:5001

POST {{Backend_HostAddress}}/api/People/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@example.com",
    "employeeId": "123457",
    "password": "1234",
    "role": "manager"
}

###

GET {{Backend_HostAddress}}/api/People

###

GET {{Backend_HostAddress}}/api/People/?role=Employee

###

GET {{Backend_HostAddress}}/api/People/?active=True

###

GET {{Backend_HostAddress}}/api/People/?role=Employee&active=true

###

PUT {{Backend_HostAddress}}/api/People/123456
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "password": "password",
    "role": "Employee"
}

###

